yarnPath: ./.yarn/releases/yarn-2.4.0.cjs
packageExtensions:
    '@dhis2/ui-forms@*':
        peerDependencies:
            '@dhis2/ui-widgets': '*'
            '@dhis2/d2-i18n': '*'
    '@dhis2/ui-icons@*':
        peerDependencies:
            '@dhis2/ui-constants': '*'
            'react': '*'
            'styled-jsx': '*'
    '@dhis2/ui-widgets@*':
        dependencies:
            'prop-types': '*'
    '@dhis2/ui-core@*':
        dependencies:
            'prop-types': '*'
