export const msgTypes = Object.freeze({
    SKIP_WAITING: 'SKIP_WAITING',
    START_RECORDING: 'START_RECORDING',
    RECORDING_STARTED: 'RECORDING_STARTED',
    RECORDING_ERROR: 'RECORDING_ERROR',
    CONFIRM_RECORDING_COMPLETION: 'CONFIRM_RECORDING_COMPLETION',
    COMPLETE_RECORDING: 'COMPLETE_RECORDING',
    RECORDING_COMPLETED: 'RECORDING_COMPLETED',
    DELETE_RECORDED_SECTION: 'DELETE_RECORDED_SECTION',
    GET_RECORDED_SECTIONS: 'GET_RECORDED_SECTIONS',
    RECORDED_SECTIONS_LIST: 'RECORDED_SECTIONS_LIST',
})

// DB and Object store name for IndexedDB
export const DB_NAME = 'recorded-section-store'
export const OS_NAME = 'recorded-sections'
