// INITIALIZATION
export const APP_LOAD_SUCCESS = 'APP_LOAD_SUCCESS'
export const APP_LOAD_ERROR = 'APP_LOAD_ERROR'

// STATISTICS
export const USAGE_DATA_REQUESTED = 'USAGE_DATA_REQUESTED'
export const USAGE_DATA_RECEIVED = 'USAGE_DATA_RECEIVED'
export const USAGE_DATA_ERRORED = 'USAGE_DATA_ERRORED'

// FILTER
export const FILTER_UPDATED = 'FILTER_UPDATED'
